# Generated by Django 4.0.4 on 2022-07-14 18:59

from django.db import migrations, models
import django.db.models.deletion
import shop.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="Категорія")),
            ],
            options={
                "verbose_name": "Категорію",
                "verbose_name_plural": "Категорії",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Кліент")),
                ("first_name", models.CharField(max_length=10, verbose_name="Ім'я")),
                ("last_name", models.CharField(max_length=10, verbose_name="Прізвище")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=10,
                        validators=[shop.utilities.validation_phone_number],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "buying_type",
                    models.CharField(
                        choices=[
                            ("Доставка", "Доставка Новою Поштою"),
                            (
                                "Самовивіз",
                                "Самовивіз, м. Одеса, вул. Преображенська 34",
                            ),
                        ],
                        default="Самовивіз",
                        max_length=100,
                        verbose_name="Тип замовлення",
                    ),
                ),
                (
                    "new_post",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Місто та номер почтового відділення",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Додати коментар до замовлення",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Активність"
                    ),
                ),
            ],
            options={
                "verbose_name": "Клієнт",
                "verbose_name_plural": "Клієнти",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="Товар")),
                ("image", models.ImageField(upload_to="", verbose_name="Головне Фото")),
                (
                    "image2",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Друге Фото"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Третьє Фото"
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Четверте Фото"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Опис товару")),
                (
                    "price",
                    models.FloatField(blank=True, null=True, verbose_name="Ціна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="shop.category",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товари",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=1, max_digits=9, verbose_name="Ціна"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Кількість"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=1, max_digits=9, verbose_name="Вартість"
                    ),
                ),
                (
                    "in_order",
                    models.BooleanField(default=False, verbose_name="Оформлено"),
                ),
                (
                    "done",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Заказ виконаний",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Активність"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop.customer",
                        verbose_name="Клієнт",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт кошику",
                "verbose_name_plural": "Продукти кошика",
            },
        ),
    ]
